name: citame
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  dio: ^5.3.3
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
    
    
  flutter_facebook_auth: ^6.0.2
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.5
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  status_alert: ^1.0.1
  web_socket_channel: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/
  uses-material-design: true