name: citame
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  dio: ^5.3.3
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1  
  fluttertoast: ^8.2.4
  oktoast: ^3.4.0
  flutter_image_compress: ^2.1.0
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.5
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  status_alert: ^1.0.1
  web_socket_channel: ^2.4.0
  flutter_animate: ^4.3.0
  flutter_local_notifications: ^16.2.0
  workmanager: ^0.5.2
  custom_clippers: ^2.0.0
  flutter_dotenv: ^5.1.0
  socket_io_client: ^2.0.3+1
  background_fetch: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/
  uses-material-design: true