// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPit-PzjjpUwn2jsCJ7bsLBj3jVdoP0Qk',
    appId: '1:937464381586:web:a70af98bbaae016b7a664b',
    messagingSenderId: '937464381586',
    projectId: 'citameprueba',
    authDomain: 'citameprueba.firebaseapp.com',
    storageBucket: 'citameprueba.appspot.com',
    measurementId: 'G-W5NDP3SH5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfX6QMBIjeMTyDZA1PIQf1FFTd6X6RzRU',
    appId: '1:937464381586:android:6ac0da4e026d2dc77a664b',
    messagingSenderId: '937464381586',
    projectId: 'citameprueba',
    storageBucket: 'citameprueba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44uRW0vsPhy98f02glCN_pnhvVeQy0fg',
    appId: '1:937464381586:ios:4cc7c86277df6f867a664b',
    messagingSenderId: '937464381586',
    projectId: 'citameprueba',
    storageBucket: 'citameprueba.appspot.com',
    iosBundleId: 'com.example.citame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44uRW0vsPhy98f02glCN_pnhvVeQy0fg',
    appId: '1:937464381586:ios:1d9d1a4db77729957a664b',
    messagingSenderId: '937464381586',
    projectId: 'citameprueba',
    storageBucket: 'citameprueba.appspot.com',
    iosBundleId: 'com.example.citame.RunnerTests',
  );
}
